@startuml

actor User
participant App as "Bookworm"
participant API as "Open Library API"

User -> App: Log in with\nemail and password
App -> App: Verify credentials
App -> Firebase: Attempt login

alt Success

    Firebase --> App: Login success
    User <- App: Logged in
    note right of User: User is redirected to\nhome screen

else Failure

    Firebase --> App: Login error
    User <- App: Display error

end

@enduml