@startuml

actor User
participant App as "Bookworm"

User -> App: Create profile with\nemail and password
App -> App: Verify credentials
App -> Firebase: Register user

alt Success

    Firebase --> App: Successful profile creation
    App -> Firestore: Create user document containing user data
    App <-- Firestore
    User <- App: Logged in
    note right of User: User is redirected to\nhome screen

else Failure

    Firebase --> App: Error creating profile
    User <- App: Display error

end

@enduml