@startuml

actor User
participant App as "Bookworm"
participant API as "Open Library API"

User -> App: Start search by\nentering character(s)

App -> API: Request search
App -> App: Save request
User <-- App: Show loading 

group Optional [User types more characters]

    User -> App: More characters
    App -> App: Cancel previous request
    App -> API: Request new search
    App -> App: Save new request

end

...

App <-- API: Search response
User <-- App: Display results

@enduml